
// Code generated by stanc v2.24.1
#include <stan/model/model_header.hpp>
namespace binomial_sepFixedWithStates_model_model_namespace {


inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 

static int current_statement__ = 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 14, column 0 to column 11)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 15, column 2 to column 17)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 16, column 2 to column 29)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 17, column 2 to column 51)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 25, column 0 to column 42)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 27, column 4 to column 87)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 26, column 17 to line 28, column 3)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 26, column 2 to line 28, column 3)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 20, column 0 to column 29)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 21, column 4 to column 37)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 22, column 4 to column 78)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 2, column 0 to column 17)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 3, column 2 to column 25)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 4, column 40 to column 41)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 4, column 2 to column 43)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 5, column 2 to column 19)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 6, column 9 to column 10)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 6, column 12 to column 13)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 6, column 2 to column 17)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 7, column 25 to column 26)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 7, column 2 to column 28)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 8, column 29 to column 30)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 8, column 2 to column 32)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 9, column 2 to column 19)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 10, column 31 to column 32)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 10, column 2 to column 34)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 11, column 9 to column 10)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 11, column 12 to column 13)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 11, column 2 to column 25)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 15, column 9 to column 10)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 17, column 35 to column 42)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedWithStates_model.stan', line 25, column 29 to column 30)"};



class binomial_sepFixedWithStates_model_model final : public model_base_crtp<binomial_sepFixedWithStates_model_model> {

 private:
  int G;
  int J_state;
  std::vector<int> state;
  int K;
  Eigen::Matrix<double, -1, -1> X;
  std::vector<int> D_votes;
  std::vector<int> Total_votes;
  int M;
  std::vector<int> predict_State;
  Eigen::Matrix<double, -1, -1> predict_X;
 
 public:
  ~binomial_sepFixedWithStates_model_model() final { }
  
  std::string model_name() const final { return "binomial_sepFixedWithStates_model_model"; }

  std::vector<std::string> model_compile_info() const {
    std::vector<std::string> stanc_info;
    stanc_info.push_back("stanc_version = stanc3 v2.24.1");
    stanc_info.push_back("stancflags = --include-paths=");
    return stanc_info;
  }
  
  
  binomial_sepFixedWithStates_model_model(stan::io::var_context& context__,
                                          unsigned int random_seed__ = 0,
                                          std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "binomial_sepFixedWithStates_model_model_namespace::binomial_sepFixedWithStates_model_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 12;
      context__.validate_dims("data initialization","G","int",
          context__.to_vec());
      G = std::numeric_limits<int>::min();
      
      current_statement__ = 12;
      G = context__.vals_i("G")[(1 - 1)];
      current_statement__ = 12;
      current_statement__ = 12;
      check_greater_or_equal(function__, "G", G, 0);
      current_statement__ = 13;
      context__.validate_dims("data initialization","J_state","int",
          context__.to_vec());
      J_state = std::numeric_limits<int>::min();
      
      current_statement__ = 13;
      J_state = context__.vals_i("J_state")[(1 - 1)];
      current_statement__ = 13;
      current_statement__ = 13;
      check_greater_or_equal(function__, "J_state", J_state, 1);
      current_statement__ = 14;
      validate_non_negative_index("state", "G", G);
      current_statement__ = 15;
      context__.validate_dims("data initialization","state","int",
          context__.to_vec(G));
      state = std::vector<int>(G, std::numeric_limits<int>::min());
      
      current_statement__ = 15;
      assign(state, nil_index_list(), context__.vals_i("state"),
        "assigning variable state");
      current_statement__ = 15;
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        current_statement__ = 15;
        current_statement__ = 15;
        check_greater_or_equal(function__, "state[sym1__]",
                               state[(sym1__ - 1)], 1);}
      current_statement__ = 15;
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        current_statement__ = 15;
        current_statement__ = 15;
        check_less_or_equal(function__, "state[sym1__]", state[(sym1__ - 1)],
                            J_state);}
      current_statement__ = 16;
      context__.validate_dims("data initialization","K","int",
          context__.to_vec());
      K = std::numeric_limits<int>::min();
      
      current_statement__ = 16;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 16;
      current_statement__ = 16;
      check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 17;
      validate_non_negative_index("X", "G", G);
      current_statement__ = 18;
      validate_non_negative_index("X", "K", K);
      current_statement__ = 19;
      context__.validate_dims("data initialization","X","double",
          context__.to_vec(G, K));
      X = Eigen::Matrix<double, -1, -1>(G, K);
      stan::math::fill(X, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 19;
        assign(X_flat__, nil_index_list(), context__.vals_r("X"),
          "assigning variable X_flat__");
        current_statement__ = 19;
        pos__ = 1;
        current_statement__ = 19;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 19;
          for (int sym2__ = 1; sym2__ <= G; ++sym2__) {
            current_statement__ = 19;
            assign(X,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              X_flat__[(pos__ - 1)], "assigning variable X");
            current_statement__ = 19;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 20;
      validate_non_negative_index("D_votes", "G", G);
      current_statement__ = 21;
      context__.validate_dims("data initialization","D_votes","int",
          context__.to_vec(G));
      D_votes = std::vector<int>(G, std::numeric_limits<int>::min());
      
      current_statement__ = 21;
      assign(D_votes, nil_index_list(), context__.vals_i("D_votes"),
        "assigning variable D_votes");
      current_statement__ = 21;
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        current_statement__ = 21;
        current_statement__ = 21;
        check_greater_or_equal(function__, "D_votes[sym1__]",
                               D_votes[(sym1__ - 1)], 0);}
      current_statement__ = 22;
      validate_non_negative_index("Total_votes", "G", G);
      current_statement__ = 23;
      context__.validate_dims("data initialization","Total_votes","int",
          context__.to_vec(G));
      Total_votes = std::vector<int>(G, std::numeric_limits<int>::min());
      
      current_statement__ = 23;
      assign(Total_votes, nil_index_list(), context__.vals_i("Total_votes"),
        "assigning variable Total_votes");
      current_statement__ = 23;
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        current_statement__ = 23;
        current_statement__ = 23;
        check_greater_or_equal(function__, "Total_votes[sym1__]",
                               Total_votes[(sym1__ - 1)], 0);}
      current_statement__ = 24;
      context__.validate_dims("data initialization","M","int",
          context__.to_vec());
      M = std::numeric_limits<int>::min();
      
      current_statement__ = 24;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 24;
      current_statement__ = 24;
      check_greater_or_equal(function__, "M", M, 0);
      current_statement__ = 25;
      validate_non_negative_index("predict_State", "M", M);
      current_statement__ = 26;
      context__.validate_dims("data initialization","predict_State","int",
          context__.to_vec(M));
      predict_State = std::vector<int>(M, std::numeric_limits<int>::min());
      
      current_statement__ = 26;
      assign(predict_State, nil_index_list(),
        context__.vals_i("predict_State"), "assigning variable predict_State");
      current_statement__ = 26;
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        current_statement__ = 26;
        current_statement__ = 26;
        check_greater_or_equal(function__, "predict_State[sym1__]",
                               predict_State[(sym1__ - 1)], 0);}
      current_statement__ = 27;
      validate_non_negative_index("predict_X", "M", M);
      current_statement__ = 28;
      validate_non_negative_index("predict_X", "K", K);
      current_statement__ = 29;
      context__.validate_dims("data initialization","predict_X","double",
          context__.to_vec(M, K));
      predict_X = Eigen::Matrix<double, -1, -1>(M, K);
      stan::math::fill(predict_X, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> predict_X_flat__;
        current_statement__ = 29;
        assign(predict_X_flat__, nil_index_list(),
          context__.vals_r("predict_X"),
          "assigning variable predict_X_flat__");
        current_statement__ = 29;
        pos__ = 1;
        current_statement__ = 29;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 29;
          for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
            current_statement__ = 29;
            assign(predict_X,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              predict_X_flat__[(pos__ - 1)], "assigning variable predict_X");
            current_statement__ = 29;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 30;
      validate_non_negative_index("beta", "K", K);
      current_statement__ = 31;
      validate_non_negative_index("aState", "J_state", J_state);
      current_statement__ = 32;
      validate_non_negative_index("predicted", "M", M);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      num_params_r__ += K;
      num_params_r__ += 1;
      num_params_r__ += J_state;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename T__>
  inline T__ log_prob(std::vector<T__>& params_r__,
                      std::vector<int>& params_i__,
                      std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "binomial_sepFixedWithStates_model_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      local_scalar_t__ alpha;
      alpha = DUMMY_VAR__;
      
      current_statement__ = 1;
      alpha = in__.scalar();
      Eigen::Matrix<local_scalar_t__, -1, 1> beta;
      beta = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      stan::math::fill(beta, DUMMY_VAR__);
      
      current_statement__ = 2;
      beta = in__.vector(K);
      local_scalar_t__ sigma_aState;
      sigma_aState = DUMMY_VAR__;
      
      current_statement__ = 3;
      sigma_aState = in__.scalar();
      current_statement__ = 3;
      if (jacobian__) {
        current_statement__ = 3;
        sigma_aState = stan::math::lb_constrain(sigma_aState, 0, lp__);
      } else {
        current_statement__ = 3;
        sigma_aState = stan::math::lb_constrain(sigma_aState, 0);
      }
      Eigen::Matrix<local_scalar_t__, -1, 1> aState;
      aState = Eigen::Matrix<local_scalar_t__, -1, 1>(J_state);
      stan::math::fill(aState, DUMMY_VAR__);
      
      current_statement__ = 4;
      aState = in__.vector(J_state);
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= J_state; ++sym1__) {
        current_statement__ = 4;
        if (jacobian__) {
          current_statement__ = 4;
          assign(aState, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::offset_multiplier_constrain(aState[(sym1__ - 1)], 0,
              sigma_aState, lp__), "assigning variable aState");
        } else {
          current_statement__ = 4;
          assign(aState, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::offset_multiplier_constrain(aState[(sym1__ - 1)], 0,
              sigma_aState), "assigning variable aState");
        }}
      {
        current_statement__ = 9;
        lp_accum__.add(normal_lpdf<propto__>(sigma_aState, 0, 10));
        current_statement__ = 10;
        lp_accum__.add(normal_lpdf<propto__>(aState, 0, sigma_aState));
        current_statement__ = 11;
        lp_accum__.add(
          binomial_logit_lpmf<propto__>(D_votes, Total_votes,
            add(add(alpha, multiply(X, beta)),
              rvalue(aState, cons_list(index_multi(state), nil_index_list()),
                "aState"))));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob() 
    
  template <typename RNG>
  inline void write_array(RNG& base_rng__, std::vector<double>& params_r__,
                          std::vector<int>& params_i__,
                          std::vector<double>& vars__,
                          bool emit_transformed_parameters__ = true,
                          bool emit_generated_quantities__ = true,
                          std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "binomial_sepFixedWithStates_model_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      double alpha;
      alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      alpha = in__.scalar();
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      beta = in__.vector(K);
      double sigma_aState;
      sigma_aState = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      sigma_aState = in__.scalar();
      current_statement__ = 3;
      sigma_aState = stan::math::lb_constrain(sigma_aState, 0);
      Eigen::Matrix<double, -1, 1> aState;
      aState = Eigen::Matrix<double, -1, 1>(J_state);
      stan::math::fill(aState, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 4;
      aState = in__.vector(J_state);
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= J_state; ++sym1__) {
        current_statement__ = 4;
        assign(aState, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::offset_multiplier_constrain(aState[(sym1__ - 1)], 0,
            sigma_aState), "assigning variable aState");}
      vars__.emplace_back(alpha);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(beta[(sym1__ - 1)]);}
      vars__.emplace_back(sigma_aState);
      for (int sym1__ = 1; sym1__ <= J_state; ++sym1__) {
        vars__.emplace_back(aState[(sym1__ - 1)]);}
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> predicted;
      predicted = Eigen::Matrix<double, -1, 1>(M);
      stan::math::fill(predicted, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 8;
      for (int p = 1; p <= M; ++p) {
        current_statement__ = 6;
        assign(predicted, cons_list(index_uni(p), nil_index_list()),
          inv_logit(
            ((alpha +
               multiply(
                 rvalue(predict_X, cons_list(index_uni(p), nil_index_list()),
                   "predict_X"), beta)) +
              aState[(predict_State[(p - 1)] - 1)])),
          "assigning variable predicted");}
      current_statement__ = 5;
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        current_statement__ = 5;
        current_statement__ = 5;
        check_greater_or_equal(function__, "predicted[sym1__]",
                               predicted[(sym1__ - 1)], 0);}
      current_statement__ = 5;
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        current_statement__ = 5;
        current_statement__ = 5;
        check_less_or_equal(function__, "predicted[sym1__]",
                            predicted[(sym1__ - 1)], 1);}
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        vars__.emplace_back(predicted[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array() 
    
  inline void transform_inits(const stan::io::var_context& context__,
                              std::vector<int>& params_i__,
                              std::vector<double>& vars__,
                              std::ostream* pstream__) const
    final {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double alpha;
      alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 2;
        assign(beta_flat__, nil_index_list(), context__.vals_r("beta"),
          "assigning variable beta_flat__");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 2;
          assign(beta, cons_list(index_uni(sym1__), nil_index_list()),
            beta_flat__[(pos__ - 1)], "assigning variable beta");
          current_statement__ = 2;
          pos__ = (pos__ + 1);}
      }
      double sigma_aState;
      sigma_aState = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      sigma_aState = context__.vals_r("sigma_aState")[(1 - 1)];
      current_statement__ = 3;
      sigma_aState = stan::math::lb_free(sigma_aState, 0);
      Eigen::Matrix<double, -1, 1> aState;
      aState = Eigen::Matrix<double, -1, 1>(J_state);
      stan::math::fill(aState, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> aState_flat__;
        current_statement__ = 4;
        assign(aState_flat__, nil_index_list(), context__.vals_r("aState"),
          "assigning variable aState_flat__");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= J_state; ++sym1__) {
          current_statement__ = 4;
          assign(aState, cons_list(index_uni(sym1__), nil_index_list()),
            aState_flat__[(pos__ - 1)], "assigning variable aState");
          current_statement__ = 4;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= J_state; ++sym1__) {
        current_statement__ = 4;
        assign(aState, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::offset_multiplier_free(aState[(sym1__ - 1)], 0,
            sigma_aState), "assigning variable aState");}
      vars__.emplace_back(alpha);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(beta[(sym1__ - 1)]);}
      vars__.emplace_back(sigma_aState);
      for (int sym1__ = 1; sym1__ <= J_state; ++sym1__) {
        vars__.emplace_back(aState[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("alpha");
    names__.emplace_back("beta");
    names__.emplace_back("sigma_aState");
    names__.emplace_back("aState");
    names__.emplace_back("predicted");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const
    final {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(J_state)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(M)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "sigma_aState");
    for (int sym1__ = 1; sym1__ <= J_state; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "aState" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "predicted" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "sigma_aState");
    for (int sym1__ = 1; sym1__ <= J_state; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "aState" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "predicted" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"sigma_aState\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"aState\",\"type\":{\"name\":\"vector\",\"length\":" << J_state << "},\"block\":\"parameters\"},{\"name\":\"predicted\",\"type\":{\"name\":\"vector\",\"length\":" << M << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"sigma_aState\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"aState\",\"type\":{\"name\":\"vector\",\"length\":" << J_state << "},\"block\":\"parameters\"},{\"name\":\"predicted\",\"type\":{\"name\":\"vector\",\"length\":" << M << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng__,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool emit_transformed_parameters__ = true,
                     bool emit_generated_quantities__ = true,
                     std::ostream* pstream = nullptr) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng__, params_r_vec, params_i_vec, vars_vec,
          emit_transformed_parameters__, emit_generated_quantities__, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = nullptr) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto__,jacobian__,T_>(vec_params_r, vec_params_i, pstream);
    }

    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__ = nullptr) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }

};
}

using stan_model = binomial_sepFixedWithStates_model_model_namespace::binomial_sepFixedWithStates_model_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

#endif


