
// Code generated by stanc v2.26.1
#include <stan/model/model_header.hpp>
namespace binomial_sepFixedOnly_loo_model_namespace {


inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 

stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 14, column 0 to column 11)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 15, column 2 to column 17)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 21, column 0 to column 18)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 23, column 4 to column 88)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 22, column 17 to line 24, column 3)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 22, column 2 to line 24, column 3)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 18, column 0 to column 56)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 2, column 0 to column 17)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 3, column 2 to column 25)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 4, column 40 to column 41)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 4, column 2 to column 43)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 5, column 2 to column 19)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 6, column 9 to column 10)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 6, column 12 to column 13)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 6, column 2 to column 17)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 7, column 25 to column 26)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 7, column 2 to column 28)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 8, column 29 to column 30)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 8, column 2 to column 32)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 9, column 2 to column 19)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 10, column 31 to column 32)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 10, column 2 to column 34)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 11, column 9 to column 10)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 11, column 12 to column 13)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 11, column 2 to column 25)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 15, column 9 to column 10)",
                                                      " (in '/Users/adam/BlueRipple/research/stan/voterPref/binomial_sepFixedOnly_loo.stan', line 21, column 7 to column 8)"};



class binomial_sepFixedOnly_loo_model final : public model_base_crtp<binomial_sepFixedOnly_loo_model> {

 private:
  int G;
  int J_state;
  std::vector<int> state;
  int K;
  Eigen::Matrix<double, -1, -1> X;
  std::vector<int> D_votes;
  std::vector<int> Total_votes;
  int M;
  std::vector<int> predict_State;
  Eigen::Matrix<double, -1, -1> predict_X;
 
 public:
  ~binomial_sepFixedOnly_loo_model() { }
  
  inline std::string model_name() const final { return "binomial_sepFixedOnly_loo_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1", "stancflags = --include-paths="};
  }
  
  
  binomial_sepFixedOnly_loo_model(stan::io::var_context& context__,
                                  unsigned int random_seed__ = 0,
                                  std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "binomial_sepFixedOnly_loo_model_namespace::binomial_sepFixedOnly_loo_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 8;
      context__.validate_dims("data initialization","G","int",
          context__.to_vec());
      G = std::numeric_limits<int>::min();
      
      current_statement__ = 8;
      G = context__.vals_i("G")[(1 - 1)];
      current_statement__ = 8;
      current_statement__ = 8;
      check_greater_or_equal(function__, "G", G, 0);
      current_statement__ = 9;
      context__.validate_dims("data initialization","J_state","int",
          context__.to_vec());
      J_state = std::numeric_limits<int>::min();
      
      current_statement__ = 9;
      J_state = context__.vals_i("J_state")[(1 - 1)];
      current_statement__ = 9;
      current_statement__ = 9;
      check_greater_or_equal(function__, "J_state", J_state, 1);
      current_statement__ = 10;
      validate_non_negative_index("state", "G", G);
      current_statement__ = 11;
      context__.validate_dims("data initialization","state","int",
          context__.to_vec(G));
      state = std::vector<int>(G, std::numeric_limits<int>::min());
      
      current_statement__ = 11;
      assign(state, nil_index_list(), context__.vals_i("state"),
        "assigning variable state");
      current_statement__ = 11;
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        current_statement__ = 11;
        current_statement__ = 11;
        check_greater_or_equal(function__, "state[sym1__]",
                               state[(sym1__ - 1)], 1);}
      current_statement__ = 11;
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        current_statement__ = 11;
        current_statement__ = 11;
        check_less_or_equal(function__, "state[sym1__]", state[(sym1__ - 1)],
                            J_state);}
      current_statement__ = 12;
      context__.validate_dims("data initialization","K","int",
          context__.to_vec());
      K = std::numeric_limits<int>::min();
      
      current_statement__ = 12;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 12;
      current_statement__ = 12;
      check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 13;
      validate_non_negative_index("X", "G", G);
      current_statement__ = 14;
      validate_non_negative_index("X", "K", K);
      current_statement__ = 15;
      context__.validate_dims("data initialization","X","double",
          context__.to_vec(G, K));
      X = Eigen::Matrix<double, -1, -1>(G, K);
      stan::math::fill(X, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 15;
        assign(X_flat__, nil_index_list(), context__.vals_r("X"),
          "assigning variable X_flat__");
        current_statement__ = 15;
        pos__ = 1;
        current_statement__ = 15;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 15;
          for (int sym2__ = 1; sym2__ <= G; ++sym2__) {
            current_statement__ = 15;
            assign(X,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              X_flat__[(pos__ - 1)], "assigning variable X");
            current_statement__ = 15;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 16;
      validate_non_negative_index("D_votes", "G", G);
      current_statement__ = 17;
      context__.validate_dims("data initialization","D_votes","int",
          context__.to_vec(G));
      D_votes = std::vector<int>(G, std::numeric_limits<int>::min());
      
      current_statement__ = 17;
      assign(D_votes, nil_index_list(), context__.vals_i("D_votes"),
        "assigning variable D_votes");
      current_statement__ = 17;
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        current_statement__ = 17;
        current_statement__ = 17;
        check_greater_or_equal(function__, "D_votes[sym1__]",
                               D_votes[(sym1__ - 1)], 0);}
      current_statement__ = 18;
      validate_non_negative_index("Total_votes", "G", G);
      current_statement__ = 19;
      context__.validate_dims("data initialization","Total_votes","int",
          context__.to_vec(G));
      Total_votes = std::vector<int>(G, std::numeric_limits<int>::min());
      
      current_statement__ = 19;
      assign(Total_votes, nil_index_list(), context__.vals_i("Total_votes"),
        "assigning variable Total_votes");
      current_statement__ = 19;
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        current_statement__ = 19;
        current_statement__ = 19;
        check_greater_or_equal(function__, "Total_votes[sym1__]",
                               Total_votes[(sym1__ - 1)], 0);}
      current_statement__ = 20;
      context__.validate_dims("data initialization","M","int",
          context__.to_vec());
      M = std::numeric_limits<int>::min();
      
      current_statement__ = 20;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 20;
      current_statement__ = 20;
      check_greater_or_equal(function__, "M", M, 0);
      current_statement__ = 21;
      validate_non_negative_index("predict_State", "M", M);
      current_statement__ = 22;
      context__.validate_dims("data initialization","predict_State","int",
          context__.to_vec(M));
      predict_State = std::vector<int>(M, std::numeric_limits<int>::min());
      
      current_statement__ = 22;
      assign(predict_State, nil_index_list(),
        context__.vals_i("predict_State"), "assigning variable predict_State");
      current_statement__ = 22;
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        current_statement__ = 22;
        current_statement__ = 22;
        check_greater_or_equal(function__, "predict_State[sym1__]",
                               predict_State[(sym1__ - 1)], 0);}
      current_statement__ = 23;
      validate_non_negative_index("predict_X", "M", M);
      current_statement__ = 24;
      validate_non_negative_index("predict_X", "K", K);
      current_statement__ = 25;
      context__.validate_dims("data initialization","predict_X","double",
          context__.to_vec(M, K));
      predict_X = Eigen::Matrix<double, -1, -1>(M, K);
      stan::math::fill(predict_X, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> predict_X_flat__;
        current_statement__ = 25;
        assign(predict_X_flat__, nil_index_list(),
          context__.vals_r("predict_X"),
          "assigning variable predict_X_flat__");
        current_statement__ = 25;
        pos__ = 1;
        current_statement__ = 25;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 25;
          for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
            current_statement__ = 25;
            assign(predict_X,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              predict_X_flat__[(pos__ - 1)], "assigning variable predict_X");
            current_statement__ = 25;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 26;
      validate_non_negative_index("beta", "K", K);
      current_statement__ = 27;
      validate_non_negative_index("log_lik", "G", G);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      num_params_r__ += K;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "binomial_sepFixedOnly_loo_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      local_scalar_t__ alpha;
      alpha = DUMMY_VAR__;
      
      current_statement__ = 1;
      alpha = in__.scalar();
      Eigen::Matrix<local_scalar_t__, -1, 1> beta;
      beta = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      stan::math::fill(beta, DUMMY_VAR__);
      
      current_statement__ = 2;
      beta = in__.vector(K);
      {
        current_statement__ = 7;
        lp_accum__.add(
          binomial_logit_lpmf<propto__>(D_votes, Total_votes,
            add(alpha, multiply(X, beta))));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "binomial_sepFixedOnly_loo_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      double alpha;
      alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      alpha = in__.scalar();
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      beta = in__.vector(K);
      vars__.emplace_back(alpha);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(beta[(sym1__ - 1)]);}
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> log_lik;
      log_lik = Eigen::Matrix<double, -1, 1>(G);
      stan::math::fill(log_lik, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 6;
      for (int g = 1; g <= G; ++g) {
        current_statement__ = 4;
        assign(log_lik, cons_list(index_uni(g), nil_index_list()),
          binomial_logit_lpmf<false>(D_votes[(g - 1)], Total_votes[(g - 1)],
            (alpha +
              multiply(
                rvalue(X, cons_list(index_uni(g), nil_index_list()), "X"),
                beta))), "assigning variable log_lik");}
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        vars__.emplace_back(log_lik[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double alpha;
      alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 2;
        assign(beta_flat__, nil_index_list(), context__.vals_r("beta"),
          "assigning variable beta_flat__");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 2;
          assign(beta, cons_list(index_uni(sym1__), nil_index_list()),
            beta_flat__[(pos__ - 1)], "assigning variable beta");
          current_statement__ = 2;
          pos__ = (pos__ + 1);}
      }
      vars__.emplace_back(alpha);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(beta[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("alpha");
    names__.emplace_back("beta");
    names__.emplace_back("log_lik");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(G)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" << G << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" << G << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  

    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        

};
}

using stan_model = binomial_sepFixedOnly_loo_model_namespace::binomial_sepFixedOnly_loo_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return binomial_sepFixedOnly_loo_model_namespace::profiles__;
}

#endif


