library(rstan)
library(shinystan)
library(loo)
setwd("/Users/adam/BlueRipple/research/georgia/stan/senateByCounty")
print("Loading csv output.  Might take a minute or two...")
stanFit <- read_stan_csv(c("output/senateByCounty_model_v1_model_1.csv","output/senateByCounty_model_v1_model_2.csv","output/senateByCounty_model_v1_model_3.csv","output/senateByCounty_model_v1_model_4.csv"))
print("Extracting log likelihood for loo...")
log_lik <-extract_log_lik(stanFit, merge_chains = FALSE)
print("Computing r_eff for loo...")
rel_eff <- relative_eff(exp(log_lik), cores = 10)
print("Computing loo..")
senateByCounty_model_v1_model <- loo(log_lik, r_eff = rel_eff, cores = 10)
print(senateByCounty_model_v1_model)
