library(rstan)
library(shinystan)
library(rjson)

setwd("/Users/adam/BlueRipple/research/stan/house/election")
print("Loading csv output.  Might take a minute or two...")
stanFit <- read_stan_csv(c("output/election_betaBinomialInc_UseBoth_2012_1.csv","output/election_betaBinomialInc_UseBoth_2012_2.csv","output/election_betaBinomialInc_UseBoth_2012_3.csv","output/election_betaBinomialInc_UseBoth_2012_4.csv"))
jsonData <- fromJSON(file = "data/election_UseBoth_2012.json")
DVotes <- append (jsonData $ DVotesE, jsonData $ DVotesC)
TVotes <- append (jsonData $ TVotesE, jsonData $ TVotesC)
print("Launching shinystan....")
launch_shinystan(stanFit)
